name: Build and Deploy Docker Image for Next2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t next2:latest .
          docker save next2:latest -o next2.tar

      - name: Upload Docker image to GitHub artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next2-image
          path: next2.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image from GitHub artifacts
        uses: actions/download-artifact@v2
        with:
          name: next2-image
          path: .

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: "next2.tar"
          target: "/root/docker_images/next2.tar"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/docker_images
            docker load -i next2.tar
            docker stop next2 || true
            docker rm next2 || true
            docker run -d -p 3004:3000 --name next2 next2:latest
